haskell/primitive

.travis.yml, Control/Monad/Primitive.hs, primitive.cabal, test/main.hs
=> Split off PrimMonadInternal haskell/vector#65

Data/Primitive/Array.hs
runST is not used in this file on GHC 7.2.x and higher, hence importing
it from Control.Monad.ST produces a warning during compilation.  This
commit makes the warning go away.
=> Condition runST import in Data/Primitive/Array.hs

cbits/primitive-memops.c, cbits/primitive-memops.h
The current implementation overflows if you try to memset a large enough array (2^32 or greater).
=> Use size_t and ptrdiff_t instead of int in cbits

Data/Primitive/Array.hs
- In GHC 7.2 and later, Array# and MutableArray# know their size, so many
classes can be instantiated for them. For 7.0 compatibility, we store a size
ourselves.
- MutableArray is also given an Eq instance
- Addresses issues #25, #30 and #32
=> Instantiate many classes for Arrays based on size

Data/Primitive/Array.hs
With the original text it was not 100% clear whether the array was boxed of the values. New text makes it explicit that its the values that are boxed.
=> Minor documentation clarification

Control/Monad/Primitive.hs
Since `IdentityT` is the most utterly boring monad transformer
possible, it actually supports a `PrimBase` instance.
=> Add PrimBase instance for IdentityT

Data/Primitive/UnliftedArray.hs, primitive.cabal
Potentially resolves #46.
Topics for discussion:
- This wrapper is type safe, homogeneous arrays of things that are wrappers around unlifted types, is there real cause for a type-unsafe, heterogeneous interface?
- This GHC API only goes back to 7.8 I believe (travis should tell us for sure). What do we do about that? Break support for 7.6 and earlier? Conditionally provide the API based on GHC version? Something else?
- I put the class that identifies unliftable things in the module that defines the unlifted arrays. It could instead go in the same place that the `Prim` class is. This would mean that each of the array types would import it and define their own instances, but that means they all have to import `unsafeCoerce#`, instead of just the one module doing that.
=> Add a type safe wrapper around ArrayArray#

primitive.cabal
base 4.10 will ship with GHC 8.2.1.
=> Bump upper bound on base

Control/Monad/Primitive.hs, changelog.md
There were missing `PrimMonad` instances for some monad transformer types:
* `ContT`
* `AccumT` and `SelectT`, which were added to `transformers` in 0.5.3
This PR adds them.
=> Add PrimMonad instances for remaining monad transformers

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
In the next version of `base` (4.11), `Semigroup` will be a superclass of `Monoid`. This PR updates `primitive` accordingly by adding missing `Semigroup` instances.
=> Adapt to the Semigroup–Monoid Proposal

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
As of GHC 8.4 Semigroup is a superclass of Monoid. Account for this
where necessary.
=> Add sconcat implementations to Semigroup instances

Data/Primitive/ByteArray.hs, test/main.hs
Implements Semigroup and Monoid instances for ByteArray described in https://github.com/haskell/primitive/issues/76
This code has not yet been tested. The functions `sconcat`, `stimes`, and `mconcat` are given implementations that are asymptotically superior to the default implementations.
=> add Semigroup and Monoid instances for ByteArray

Data/Primitive/Addr.hs, Data/Primitive/ByteArray.hs
Resolves https://github.com/haskell/primitive/issues/80
Currently, this does not provide these functions for users of older GHCs. I'm not sure if this how important this is. Also, I'm not sure when the primitives for copying between a byte array and an address were introduced to `ghc-prim`. I guessed GHC 7.2, but hopefully travis will let me know if I guessed wrong.
=> Copy bytearray addr

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
* Index `Array`s and `SmallArray`s eagerly.
* Fix `foldl1` for `Array`, which was completely wrong.
* Make the structure of the `Foldable` instances for `Array`
and `SmallArray` the same, taking what I thought was the best
from each.
Fixes #86
=> Fold better; fix foldl1 bug

.travis.yml, cabal.project, primitive.cabal, test/LICENSE, test/primitive-tests.cabal
This is a preparatory refactor towards #89. This moves the test suite into a separate `.cabal` file so that in the future, we can modify the test suite to depend on libraries that depend on `primitive` itself, such as `QuickCheck`.
Note that this does not change any of the code in the test suite itself—let's save that for a separate commit.
=> Move tests to separate .cabal file 

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
* Instead of traversing a list and then converting to an array,
be more direct. GHC seems to be able to optimize this better,
at least in common cases.
* Add functions for traversing arrays in "affine" primitive monads: monad transformer stacks built from `StateT`, `ReaderT`, `WriterT`, `RWST`, `ExceptT`, `Stream (Of a)`, etc., but not, for example, `ListT` (done right or otherwise) or `LogicT`.
Fixes #85.
=> Traverse better

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
* Perform array indexing eagerly in general to avoid
useless thunks.
* Make `munzip` stricter for `Array`, to match the
`SmallArray` instance and avoid loads of thunks.
* Give `Array` and `SmallArray` much less inefficient
`MonadFix` instances. Leaning on the instance for `[]`
is bad because indexing into lists is expensive, and that's
effectively what the `MonadFix` instance does.
=> More eagerness

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs
=> Make array creation friendlier to worker-wrapper

Data/Primitive/ByteArray.hs
This provides access to the `resizeMutableByteArray#` primop added in GHC 7.10.
Note that this operation, like the underlying primop, doesn't preserve pinned-ness. Another alternate design would be to pin the new array if the original was pinned. However, it is unfortunately not possible to provide these semantics consistently across GHC versions since `isByteArrayPinned#` was only added in GHC 8.0.
=> Implement resizeMutableByteArray

.travis.yml, bench/Array/Traverse/Closure.hs, bench/Array/Traverse/Compose.hs, bench/Array/Traverse/Unsafe.hs, bench/ByteArray/Compare.hs, bench/LICENSE, bench/README.md, bench/main.hs, bench/primitive-benchmarks.cabal, cabal.project, test/primitive-tests.cabal
Benchmark performance difference between closure-building array traversal and the unsafe PrimMonad variant. Currently, `cabal new-build` fails to build this if you are using GHC 8.0 or newer because of something going on in `basement` (which `gauge` depends on). I'm sure this will be resolved soon. For now, we can do:
```
$ cabal new-build bench --enable-benchmarks -w ghc-7.10.3
$ ./dist-newstyle/build/x86_64-linux/ghc-7.10.3/primitive-benchmarks-0.1/c/bench/build/bench/bench
benchmarked Array/traverse/closure
time                 929.5 μs   (913.6 μs .. 948.6 μs)
0.998 R²   (0.998 R² .. 0.999 R²)
mean                 910.4 μs   (906.5 μs .. 916.2 μs)
std dev              15.65 μs   (10.99 μs .. 20.36 μs)
benchmarked Array/traverse/unsafe
time                 360.6 μs   (357.1 μs .. 363.8 …
```
=> Add benchmark suite

Data/Primitive.hs, changelog.md
resolves https://github.com/haskell/primitive/issues/125
=> reexport SmallArray and UnliftedArray types and functions from Data.Primitive

test/main.hs
Write tests to ensure that the implementation of resizeByteArray on older GHCs, which uses a shim, behaves the same as the implementation on newer GHCs, which uses a primop.
Resolves https://github.com/haskell/primitive/issues/115.
=> Test resizeByteArray

Data/Primitive/Ptr.hs, changelog.md, primitive.cabal
This PR provides functions for working with `Ptr` that take a `Prim` constraint instead of a `Storable` constraint. My motivation for this is that at work, I've ended up in situations where I've got a `Ptr` and a `MutableByteArray` referring to elements of the same type. It's weird to carry around both the `Storable` constraint and the `Prim` constraint in these situations especially because the two instances always agree with one another. To avoid the `Storable` constraint, I usually end up casting the `Ptr` to an `Addr`. This is boilerplate I would like to avoid, and it makes the whole process a little more error-prone.
Questions:
- Do other people think this is a good idea?
- Should these functions operate in `PrimMonad`, or should these be constrained to `IO`?
=> Data.Primitive.Ptr

Control/Monad/Primitive.hs, Data/Primitive.hs, Data/Primitive/PrimArray.hs, bench/PrimArray/Traverse.hs, bench/main.hs, bench/primitive-benchmarks.cabal, changelog.md, primitive.cabal, test/main.hs, test/primitive-tests.cabal
This was original requested in https://github.com/haskell/primitive/issues/58 and was received positively. Indeed, it appears that at three different authors have built nearly the same thing in the wild. This feature was implemented as a part of the larger and more ambitious https://github.com/haskell/primitive/pull/64, which eventually stalled. As @treeowl [commented](https://github.com/haskell/primitive/pull/64):
> This pull request is very large. Lots of new functionality. I suspect it might be better to break it up.
This is an attempt at precisely that. All that is implemented here is `PrimArray`. Discussion of design choices:
- In this PR, `PrimArray` is implemented as a data type on top of `ByteArray#`, not as a newtype on top of `ByteArray`. This makes some of the `Monoid` and …
=> Implement PrimArray

Data/Primitive.hs
This has been bothering me for a while.
=> eliminate needless reexport of sizeOf and alignment from Data.Primitive

Data/Primitive/Types.hs, test/main.hs
Resolves https://github.com/haskell/primitive/issues/130
My preference is actually to let this sit for a while to make sure that the final implementation of `DerivingVia` actually matches what is suggested in the documentation this PR provides.
=> Add PrimStorable for deriving getting a Storable instance from a Prim instance

Data/Primitive/Ptr.hs
I started compiling my stuff start currently uses `prim-array` against the master branch of `primitive`, and I realized that I had forgotten to implement `copyPtrToMutablePrimArray` in `Data.Primitive.Ptr`. This happened because I was working on the `PrimArray` module and the `Ptr` module in separate branches at the same time. Anyway, this PR provides the missing wrapper around `copyAddrToByteArray#`.
=> Add function for copying from Ptr to MutablePrimArray

Control/Monad/Primitive.hs, Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/SmallArray.hs, Data/Primitive/Types.hs
@andrewthad added `since` metadata for everything coming up in 0.6.4.0, this PR adds stuff for 0.6.0.0 to 0.6.3.0
=> add since metadata from 0.6 to 0.6.3

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs, Data/Primitive/UnliftedArray.hs
This superceeds https://github.com/haskell/primitive/pull/161 It makes `PrimArray`'s `Ord` instance use a lexicographic ordering, and it documents what ordering all of the array types use for their `Ord` instances.
=> Ord Instance Documentation

Data/Primitive/PrimArray.hs, bench/PrimArray/Compare.hs, bench/main.hs, bench/primitive-benchmarks.cabal
Also, this PR adds missing `INLINE` pragmas for the implementations of `compare` and `==` for `PrimArray`. I noticed they were missing, and it made them run way slower.
Sadly, the benchmarks do not actually show what I hoped they would. I thought that overriding the default implementation of `<` and `<=` would make them faster, but this does not appear to be the case:
```
benchmarked PrimArray/implementations/less-than/default
time                 4.403 μs   (4.381 μs .. 4.426 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 4.426 μs   (4.411 μs .. 4.453 μs)
std dev              66.35 ns   (39.42 ns .. 97.83 ns)
benchmarked PrimArray/implementations/less-than/override
time                 4.379 μs   (4.368 μs .. 4.392 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean …
```
=> add benchmarks for different implementations of inequality functions

Data/Primitive/MutVar.hs
A recent [commit](https://github.com/ghc/ghc/commit/af9b744bbf1c39078e561b19edd3c5234b361b27) in ghc removed `GHC.Prim.atomicModifyMutVar#` which breaks `Data.Primitive.MutVar`. An implementation of `atomicModifyMutVar#` is provided in `GHC.Exts` instead, so I intend to fix the build error by simply replacing `GHC.Prim` with `GHC.Exts`.
=> Fix build error by recent ghc-head

Data/Primitive/UnliftedArray.hs
When using GHC versions before 7.10, `SmallArray` is a newtype
wrapper around `Array`, and similarly `SmallMutableArray` is a
newtype wrapper around `MutableArray`. So the `PrimUnlifted`
instances need to go through two layers of constructors to get
to an unlifted type. Previously we failed to do that, leading
to invalid and dangerous coercions.
Fixes #199
=> Fix PrimUnlifted instances for small arrays

Data/Primitive/Types/PrimUnlifted.hs, Data/Primitive/UnliftedArray.hs, primitive.cabal
The `PrimUnlifted` class, used to implement `UnliftedArray`
operations, is currently based on an `ArrayArray#` representation
of unlifted arrays. But that's set to change, hopefully soon.
I don't think it's too soon to set up the machinery necessary to
allow users to write code *today* that will work once `ArrayArray#`
is gone.
The key here is to add an associated type family to `PrimUnlifted`
that ties each `LiftedRep` type to its `UnliftedRep` counterpart,
and methods that convert back and forth.
=> Set the stage for UnliftedArray#

Data/Primitive/Internal/Operations.hs, Data/Primitive/Types.hs, Data/Primitive/Types/PrimUnlifted.hs, changelog.md, test/main.hs
Add a `Prim` instance for `StablePtr` and a `PrimUnlifted`
instance for `StableName`.
Closes #201
=>  Add Prim instances for stable things

Data/Primitive/Array.hs
Related question on [StackOverflow](https://stackoverflow.com/questions/53734159/subtle-difference-between-copymutablearray-and-copymutablearray). I hope such a small fix doesn't have to go through the libraries mailing list :sweat_smile: .
=> Fix documentation comment for copyMutableArray.

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs, changelog.md, primitive.cabal
`base-4.13` will finally complete the `MonadFail` proposal by removing the `fail` method from `Monad`. This adapts `primitive` to that change by guarding the existing `fail` implementations in `primitive` (for `Array` and `SmallArray`) behind CPP, and defining `MonadFail` instances for `Array` and `SmallArray` going forward.
=> Adapt to MonadFail-related changes in base-4.13

Control/Monad/Primitive.hs
Add `PrimMonad` instances for `Control.Monad.Trans.Writer.CPS`
and `Control.Monad.Trans.RWS.CPS`.
Closes #226
=> Add CPS transformer variants

Control/Monad/Primitive.hs, changelog.md
`unsafeCoerce#` can no longer be imported from `GHC.Base` on GHC HEAD, so this patch changes the import to `GHC.Exts` instead. While I was in town, I removed some unnecessary CPP (`primitive` supports GHC 7.4 as the minimum, so `MIN_VERSION_base(4,2,0)` and `MIN_VERSION_base(4,4,0)` are always true) and consolidated some other `GHC.Base` imports to use `GHC.Exts` instead.
Fixes #258.
=> Use GHC.Exts to import unsafeCoerce# et al.

Data/Primitive/Types.hs, test/main.hs
For GHC 7.6 and up, use GHC.Prim.setByteArray# instead of the FFI to fill byte arrays with Int8 and Word8. This also adds some tests to confirm that the behavior has not changed.
=> For GHC 7.6 and up, use GHC.Prim.setByteArray#

cbits/primitive-memops.h
Otherwise things may break on Windows. For instance,
you may get things like,
```
includes\stg\Types.h:26:9: error:
warning: #warning "Mismatch between __USE_MINGW_ANSI_STDIO
definitions. If using Rts.h make sure it is the first header
included." [-Wcpp]
```
=> Ensure that HsFFI.h is #include'd first

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs, changelog.md
This adds `NFData` instances for `Array` and `SmallArray` as suggested by @andrewthad. I'm not too familiar with using CPP for supporting many versions so I'm happy to fix glaring errors.
=> Add NFData instances for Array and SmallArray

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs
This adds documentation to some undocumented functions. It also adds notes that bounds (and other) checks are not performed (#212). In #212 it was mentioned that the intended audience already knows what they are doing but I think it is nevertheless useful to mentio and has no particular downsides. I may have gotten some of the checking notes wrong so let me know if so.
=> Add documentation

Data/Primitive/ByteArray.hs
This PR implements a simple fix for #286
=> Fix integer overflow in `moveByteArray`

Control/Monad/Primitive.hs
cc @emilypi @treeowl 
I think we just auto-fundep'd based on MTL. it is indeed unnecessary.
=> remove fundep on MonadPrim

primitive.cabal
=> Make test suite depend on semigroups only on GHC < 8.0

primitive.cabal
Bump upper bound to build with `ghc-9.0`.
=> Bump upper bounds on base

Data/Primitive/Internal/Operations.hs, Data/Primitive/Types.hs, cbits/primitive-memops.c, cbits/primitive-memops.h
Hi there,
I gave it a shot at fixing #302. This is all pretty naive as I am still not very familiar with GHC primitives. It compiles and passes tests on GHC 8.8, GHC 8.10, GHC 9.0. For GHC 9.2 I haven't managed to run the tests yet because the `bifunctor` doesn't compile on GHC 9.2 (due to some changes to `template-haskell`). I might do some manual testing.
=> Support GHC 9.2

Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, changelog.md
Fixes #307.
I added `thawByteArray` and `thawPrimArray`. The implementation is just new + copy, similar to the respective freeze variant. The doc comments are essentially copied from `thawArray`.
I also fixed some typos in `Data.PrimArray` that i noticed, where "byte" was used instead of "primitive"/"prim".
=> Add thawByteArray, thawPrimArray

Data/Primitive/ByteArray.hs, changelog.md, test/main.hs
Previously, the Show instance for ByteArray would produce results like [0xb, 0x1f, 0x5]. Now, it produces [0x0b, 0x1f, 0x05].
=> Zero-pad words encoded in ByteArray Show instance

Data/Primitive/PrimArray.hs
Previously, the `Lazy Applicative` section wasn't shown.
=> Fix Haddock bug

Data/Primitive/Array.hs, Data/Primitive/SmallArray.hs, test/main.hs
The implementations of `*>` for `Array` and `SmallArray` were buggy:
* `Array`: The bug was caused by not calling `go (i + 1)`.
* `SmallArray`: The bug was caused by using `0` instead of `i * lb` as offset when calling `copySmallArray` in the implementation of `*>`.
I also did some minor formatting changes.
Btw, is there any particular reason for using `fix` instead of defining a recursive `go` function directly?
=> Fix bugs in `*>`

Control/Monad/Primitive.hs, Data/Primitive.hs, Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/Internal/Compat.hs, Data/Primitive/Internal/Operations.hs, Data/Primitive/MVar.hs, Data/Primitive/MachDeps.hs, Data/Primitive/MutVar.hs, Data/Primitive/PrimArray.hs, Data/Primitive/Ptr.hs, Data/Primitive/SmallArray.hs, Data/Primitive/Types.hs, Setup.hs, cbits/primitive-memops.h, primitive.cabal
Changes:
* fix doc comments (add missing periods, fix grammar issues)
* add missing doc comments for `sizeofArray`, `sizeofMutableArray`, `sizeofSmallArray`, `sizeofSmallMutableArray` and `MVar`
* extend doc comments for underdocumented functions
* remove `Setup.hs` (it's not used afaict)
* remove unnecessary imports
* format (I tried to keep the original style, I mostly did stuff like adding spaces around operators and after commas)
=> Improve documentation & format

primitive.cabal
I just tried to build it against lts-11.22 (which has `Cabal-2.0.1.0`) and it did build just fine, so I don't see a reason to set it higher than necessary.
=> Relax minimum cabal version

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/SmallArray.hs, test/main.hs
* add `stimes` definition for `Array` & `SmallArray`
* change `stimes` definition for `ByteArray` (and thus also for `ByteArray`) to error for negative multipliers and not check for overflow (no other `primitive` functions check for overflows, so this seems pointless)
* add property tests for `stimes` & `semigroupLaws`
=> Add/update definitions for `stimes`

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/Ptr.hs, Data/Primitive/SmallArray.hs, primitive.cabal
=> Add Lift instances

test/main.hs
Followup to #326.
The test suite would previously fail on 7.10, because I forgot to put the `semigroupLaws` test inside a `#if` block (sorry).
=> Fix `semigroupLaws` tests

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs, Data/Primitive/Types.hs, primitive.cabal, test/main.hs
Resolves #337.
This also gets rid of a bunch of CPP. I bumped the version bounds to be appropriate for base >= 4.9.
=> Drop support for GHC 7.10

primitive.cabal
The current release on Hackage fails to build with 9.4, but the version on `master` works fine with `--allow-newer` (with a few warnings about some new syntax).
Omitting `--allow-newer` gives us an error with QuickCheck and `splitmix`, but those are also fine for now.
=> GHC 9.4 support

Data/Primitive/ByteArray.hs
=> Fix size computation in `copyByteArrayToPtr` & `copyMutableByteArrayToPtr`

changelog.md
Add more details to the changelog. Document resizeSmallMutableArray and explain why PrimVar is useful.
I will release 0.8.0.0 soon.
=> Prepare for 0.8.0.0 release

.github/workflows/ci.yml, cabal.project, primitive.cabal
- bump outdated actions
- get GHC 9.6.0 from ghcup prerelease channel
- bumps to allow GHC 9.6.0
=> Extend CI to GHC 9.6.1 alpha2

Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/Ptr.hs, Data/Primitive/Types.hs, test/main.hs, test/src/PrimLaws.hs
Closes #344.
This adds `sizeOfType` and `alignmentOfType` "methods" to the `Prim` class. They're `Int` values, since class dictionaries apparently can't contain unboxed values, but I'm doubtful that `Int#` would bring any advantages anyway. I chose the `OfType` suffix to indicate that they're about the size/alignment *of a type* and that they need a *type* argument (via `TypeApplications`). I also added doc comments to encourage the use of these new values.
The PR is marked as draft, since I first want to get the new definitions reviewed, before changing uses of `sizeOf`/`sizeOf#` and `alignment`/`alignment#` throughout the package.
EDIT: As per @lehins suggestion, I added `sizeOfType#` and `alignmentOfType#` methods instead and made `sizeOfType` and `alignmentOfType` standalone values.
=> Add `sizeOfType`, `alignmentOfType`

Data/Primitive/Array.hs, Data/Primitive/Internal/Read.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs, changelog.md, primitive.cabal
Resolves https://github.com/haskell/primitive/issues/388
Remarkably, this accidentally unearthed a mistake in the `Read` implementations for `Array` and `SmallArray`. Anyone interested in that can look at the diff. I rewrote the `Read` instance for `SmallArray` entirely to just copy what `Array` was doing.
=> Change Show instances for Array, SmallArray, PrimArray

Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs
I just had a bug, because I assumed `ByteArray`s/`PrimArray`s were initialized with zeros. Unfortunately, the documentation didn't mention that they're uninitialized (except for `newPrimArray`).
=> Clarify that newly allocated `ByteArray`s/`PrimArray`s are uninitialized

primitive.cabal, test/Main.hs
Closes #111.
Replace `Proxy1` by `Proxy1` (`Proxy` is poly-kinded now).
=> Test `alternativeLaws`, `monadZipLaws`, `monadPlusLaws`

primitive.cabal
Only makes the library itself build. The test suite has broken dependencies, some of which in turn have broken dependencies.
=> Make it build with ghc-9.8

Data/Primitive/ByteArray.hs
(The function documentation already demands "The two slices may not overlap.")
=> Use `copyMutableByteArrayNonOverlapping#` when available

Data/Primitive/ByteArray.hs
The primop in question appears to have always been safe for use with overlapping ranges since its introduction. See also: https://gitlab.haskell.org/ghc/ghc/-/commit/b00b36196a88ad6b9054244caaec926f6f9db2cf
The cbits function "hsprimitive_memmove" is now unused, but is not removed because it was arguably publicly exposed due to the "Install-Includes: primitive-memops.h".
=> Use `copyMutableByteArray#` in moveByteArray

Control/Monad/Primitive.hs, Data/Primitive.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs
Fix all broken Haddock links. Now Haddock doesn't emit any warnings about out-of-scope identifiers. Warnings about unknown link destinations are more complicated to resolve and are not handled in this PR.
=> Fix broken Haddock links

primitive.cabal
This is useless at best, and a common source of confusion.
https://github.com/haskell/cabal/pull/10145
https://github.com/sol/hpack/issues/355
=> Remove `includes` from `.cabal`-file

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs
...in terms of list fusion.
Closes #418.
Note: Compared to the proposed change in #418, this PR also uses `GHC.Exts.oneShot`. GHC doesn't need this help if the input is just a list, but I have found that it can improve performance after fusion reduces it to a foldr on another structure, such as a Set. Benchmarks showing this effect: [gist](https://gist.github.com/meooow25/161df9be185b4cba6e99922075d4bc1c#file-z-output-txt)
=> Make fromListN functions good consumers

Data/Primitive/Array.hs, Data/Primitive/ByteArray.hs, Data/Primitive/PrimArray.hs, Data/Primitive/SmallArray.hs, Data/Primitive/Types.hs, primitive.cabal, test/Main.hs
The test suite dependency on ghc-prim has been removed. An import of Data.Ord in the test suite has been removed. All shims for GHC 8.0 have been removed.
=> Remove unused imports, dead code, and unused deps

Data/Primitive/ByteArray.hs, changelog.md
Also, add mutableByteArrayAsForeignPtr for symmetry with byteArrayAsForeignPtr.
=> Prepare changelog for 0.9.1.0
