haskell/primitive

Control/Monad/Primitive.hs

Switching to the approved "better" name.

Renamed PrimMonadInternal to PrimBase

---

primitive.cabal

Allow for ghc-prim 0.4

---

Data/Primitive/Array.hs

GHC has primops for these going back to 7.2.

Add freezeArray and thawArray to Data.Primitive.Array

---

Data/Primitive/SmallArray.hs
primitive.cabal

This addresses issue #20.
How do we feel about the loops? (Note, I checked the core, and they look just as good as named definitions; so that's not an issue.)

Add support for small arrays

---

Data/Primitive/Types.hs

Add Prim instances for Ptr and FunPtr

---

Control/Monad/Primitive.hs

Generalize `Control.Exception.evaluate`.

Add evalPrim

---

Control/Monad/Primitive.hs

Add ioToPrim, stToPrim, and unsafe counterparts

---

Data/Primitive.hs
Data/Primitive/ByteArray.hs
Data/Primitive/Types.hs
cbits/primitive-memops.c
cbits/primitive-memops.h
test/main.hs

Add `Eq`, `Ord`, and `Show` instances for `ByteArray`.

ByteArray instances

---

Data/Primitive/Array.hs

`fmap` for `Array` got its indexing all wrong. Fix that. Fix an infinite loop in `>>=` for `Array`.
Fixes #92 and #95

Fix fmap for Array

---

Data/Primitive/ByteArray.hs

Resolves https://github.com/haskell/primitive/issues/115

correct the shim for resizeMutableByteArray

---

Data/Primitive/Types.hs
changelog.md

Additional Prim instances for newtypes in base

---

Data/Primitive/Addr.hs
Data/Primitive/ByteArray.hs
Data/Primitive/Types.hs

Fix a variety of papercuts I recently encountered.
Also fix documentation shortcoming.
Continuation of #57.

Useful Addr functions

---

Data/Primitive/ByteArray.hs
changelog.md

Resolves https://github.com/haskell/primitive/issues/113.

implement isByteArrayPinned and isMutableByteArrayPinned

---

Data/Primitive/ByteArray.hs

Resolves https://github.com/haskell/primitive/issues/54

Warn against the dangers of sizeofMutableByteArray

---

Data/Primitive/UnliftedArray.hs
changelog.md

Resolves https://github.com/haskell/primitive/issues/75

add PrimUnlifted instances for TVar and MVar

---

Data/Primitive/Array.hs
Data/Primitive/SmallArray.hs

Resolves https://github.com/haskell/primitive/issues/134

rename unsafe traversals

---

Data/Primitive/Array.hs
Data/Primitive/SmallArray.hs
bench/Array/Traverse/Closure.hs

Resolves https://github.com/haskell/primitive/issues/140

export unary tuple indexing functions for Array and SmallArray

---

Data/Primitive/SmallArray.hs
changelog.md

Resolves https://github.com/haskell/primitive/issues/155

fix broken mconcat for SmallArray

---

Data/Primitive/PrimArray.hs
Data/Primitive/UnliftedArray.hs
changelog.md
test/main.hs

This adds fold functions and a map function to `UnliftedArray`. It also adds more typeclass instances.

Unlifted array functions

---

Data/Primitive/Addr.hs
Data/Primitive/Array.hs
Data/Primitive/ByteArray.hs
Data/Primitive/MVar.hs
Data/Primitive/PrimArray.hs
Data/Primitive/Ptr.hs
Data/Primitive/SmallArray.hs
Data/Primitive/UnliftedArray.hs

Related to https://github.com/haskell/primitive/issues/124

add since pragmas to everything introduced in primitive-0.6.4.0

---

Data/Primitive/Types.hs
cabal.project
changelog.md
test/main.hs

Resolves https://github.com/haskell/primitive/issues/84

Default prim implementations

---

changelog.md

Resolve https://github.com/haskell/primitive/issues/171

add mvar to changelog

---

Data/Primitive/Types.hs

I forgot to add since pragmas for the newtype instances that were just merged. This PR adds those

add @since pragmas for newtypes

---

Data/Primitive/MutVar.hs

`atomicModifyMutVar'` was rather lazier than intented.
Copy the correct implementation over from `base`.

Fix atomicModifyMutVar'

---

Data/Primitive/UnliftedArray.hs
changelog.md

Resolves https://github.com/haskell/primitive/issues/195

remove PrimUnlifted instance for StablePtr

---

Data/Primitive/Types/PrimUnlifted.hs

GHC 8.6 will export the `StableName` constructor from
`GHC.StableName`, meaning we won't have to pull an ugly
`unsafeCoerce` trick to get at its guts.

Use newly-exported StableName constructor

---

Data/Primitive/Array.hs

Use the `ReadPrec` mechanism instead of the `ReadS` one. Allow reading
"`OverloadedList` style" and "`OverloadedString`" style, along with
`fromList` and `fromListN` style.
Fixes #223

Read arrays more flexibly

---

Data/Primitive/Types.hs

Resolves https://github.com/haskell/primitive/issues/230

Document platform-dependent endianness

---

Control/Monad/Primitive.hs
Data/Primitive/Addr.hs
Data/Primitive/Array.hs
Data/Primitive/ByteArray.hs
Data/Primitive/Internal/Operations.hs
Data/Primitive/MachDeps.hs
Data/Primitive/MutVar.hs
Data/Primitive/PrimArray.hs
Data/Primitive/Ptr.hs
Data/Primitive/Types.hs
test/main.hs

this builds on my machine with GHCs 7.4.2 through 8.6.4.

remove all imports of GHC.Prim (GHC.Prim ==> GHC.Exts). resolves #197

---

Control/Monad/Primitive.hs
changelog.md

fix: #24
Code is @treeowl's from https://github.com/haskell/primitive/issues/24#issuecomment-276155819

Add instances for lazy ST

---

Control/Monad/Primitive.hs
changelog.md

Remove Lazy ST instance on GHC 8.2

---

Data/Primitive/ByteArray.hs
Data/Primitive/PrimArray.hs
changelog.md
primitive.cabal

This adds an NFData instance. It is quite naive so I welcome feedback on important considerations (either with versions or just using `rwhnf`).

Add NFData instance (#267)

---

Data/Primitive/Types.hs
changelog.md

Resolves https://github.com/haskell/primitive/issues/249

Add Prim instances for WordPtr and IntPtr

---

Control/Monad/Primitive.hs

Resolves https://github.com/haskell/primitive/issues/53

Document abysmal soundness guarantees of unsafeInlineIO

---

Data/Primitive/Array.hs
changelog.md

This is the first step of https://github.com/haskell/primitive/issues/132

Export arrayFromList and arrayFromListN

---

primitive.cabal

Related to commercialhaskell/stackage#5795; I haven't tested this locally, I just figured it would be easy to make the change and let CI yell at me if something broke.

Allows tasty 1.3 & 1.4

---

Data/Primitive/Internal/Operations.hs
Data/Primitive/Types.hs
cbits/primitive-memops.c
cbits/primitive-memops.h
primitive.cabal

I forgot to bump the upper bound on base after adding support for GHC 9.2 in #303

Bump upper bound on base

---

Data/Primitive/Array.hs
Data/Primitive/ByteArray.hs
Data/Primitive/PrimArray.hs
Data/Primitive/SmallArray.hs
changelog.md

Closes #185.
Export `runByteArray`, `runPrimArray`, `emptyByteArray`, `emptyPrimArray`, `emptyArray` and `emptySmallArray`. I also added doc comments.
EDIT: Also export `createArray` and `createSmallArray`.

Export some useful functions

---

Data/Primitive/Array.hs
Data/Primitive/SmallArray.hs

Forgot to force on a single-element lift.

Fix strictness mistake

---

.github/workflows/ci.yml
primitive.cabal

Explicitly test 9.2 and update actions & `tested-with`.

Test GHC 9.2 in CI

---

Control/Monad/Primitive.hs
changelog.md
primitive.cabal

Add keepAlive

---

Data/Primitive/SmallArray.hs

Docs are just copied from GHC. Any suggestions to do better job on them are welcome.

Expose ‘resizeSmallMutableArray’

---

Control/Monad/Primitive.hs
Data/Primitive/Array.hs
Data/Primitive/ByteArray.hs
Data/Primitive/PrimArray.hs
Data/Primitive/SmallArray.hs
cabal.project
primitive.cabal

Fix some warnings for GHC 8.0, 8.4 up, 9.4, to be included in next release.

Fix some warnings for GHC 8.0, 8.4 up, 9.4

---

Data/Primitive/PrimArray.hs
Data/Primitive/Types.hs

Clean up import warnings for GHC 9.6

---

Control/Monad/Primitive.hs
changelog.md
primitive.cabal

Addresses the issue discussed in the conversation starting with [this comment](https://github.com/haskell/primitive/pull/363#issuecomment-1476951030).
cc @andrewthad @treeowl @mitchellwrosen for review
cc @bgamari for thoughts as well

fix type signature of keepAlive

---

Control/Monad/Primitive.hs
Data/Primitive/Internal/Operations.hs

Adds `keepAliveUnlifted` and `touchUnlifted`. Introduces some internally used wrapper for `keepAlive` that make it easier to see that coercions that happen.

Introduce more variants of keepAlive and touch

---

Data/Primitive/Array.hs
Data/Primitive/SmallArray.hs

Relax constraints for array indexing to `Applicative`

---

Data/Primitive/ByteArray.hs
Data/Primitive/PrimArray.hs

Add createPrimArray and createByteArray

---

Data/Primitive/MutVar.hs

Resolves https://github.com/haskell/primitive/issues/422

Improve MutVar interop with IORef and STRef
